apiVersion: apps/v1
kind: Deployment
metadata:
  name: pods-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pods-backend
  template:
    metadata:
      labels:
        app: pods-backend
    spec:
      containers:
        - name: backend
          image: pods-backend:latest
          ports:
            - containerPort: 4000
