apiVersion: apps/v1
kind: Deployment
metadata:
  name: pods-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pods-frontend
  template:
    metadata:
      labels:
        app: pods-frontend
    spec:
      containers:
        - name: frontend
          image: pods-frontend:latest
          ports:
            - containerPort: 3000
